image: "rust:latest"

test:cargo:
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential cmake pkg-config libssl-dev linkchecker
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  script:
  - rustc --version && cargo --version
  - cargo test --all
  - cargo doc
  - linkchecker target/doc/serde_any/
  - cargo tarpaulin --out Xml
  - "bash <(curl -s https://codecov.io/bash)"

test:features:
  script:
  - rustc --version && cargo --version
  - cargo build --no-default-features
  - cargo build --no-default-features --features=json
  - cargo build --no-default-features --features=yaml
  - cargo build --no-default-features --features=toml
  - cargo build --no-default-features --features=ron
  - cargo build --no-default-features --features="json, yaml"
  - cargo build --no-default-features --features="toml, ron"
  - cargo build --no-default-features --features="json, yaml, toml, ron"
