[package]
name = "serde_any"
version = "0.1.1"
authors = ["Miha Čančula <miha@noughmad.eu>"]
license = "MIT/Apache-2.0"
description = "Dynamic serialization and deserialization with the format chosen at runtime"
repository = "https://gitlab.com/Noughmad/serde_any"
keywords = ["serde", "serialization", "json", "toml", "yaml"]
categories = ["encoding"]
readme = "README.md"

[badges]
gitlab = { repository = "Noughmad/serde_any", branch = "master" }
codecov = { repository = "Noughmad/serde_any", branch = "master", service = "gitlab" }

[features]
default = ["toml", "json", "yaml", "ron"]
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
serde = "1"
toml = { version = "0.4", optional = true }
serde_json = { version = "1", optional = true }
serde_yaml = { version = "0.7", optional = true }
ron = { version = "0.3", optional = true }
failure = "0.1.1"

[dev-dependencies]
serde_derive = "1"
