[package]
name = "serde_any"
version = "0.1.0"
authors = ["Miha Čančula <miha@noughmad.eu>"]

[features]
default = ["toml", "json", "yaml"]
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
serde = "1"

toml = { version = "0.4", optional = true }
serde_json = { version = "1", optional = true }
serde_yaml = { version = "0.7", optional = true }
failure = "0.1.1"
